### PR TITLE
Make conceal work on 64 bit archs

### PR DESCRIPTION
**Pull request by siyengar**
Based on https://github.com/facebook/conceal/pull/73

### CODE REVIEW

**Comment by MangeshKadam** [comment]
@siyengar - when we can expect merging of pull request 101? we are eagerly waiting for this to fix.
Thanks.

**Comment by siyengar** [comment]
@MangeshKadam I'm waiting for a review from @mburman. It's the weekend here, so I anticipate on Monday.

**Comment by ahmednasir91** [comment]
@siyengar is it possible to push a new version to maven?

**Comment by siyengar** [comment]
Ya i released it under 1.0.2 a new version which you should be able to pick up shortly

**Comment by ahmednasir91** [comment]
@siyengar alright waiting for it. Thanks

**Comment by MangeshKadam** [comment]
Hi @siyengar . I just tried 1.0.2 version. AAR file does not contains jni folder so the library. Is that expected?

**Comment by ahmednasir91** [comment]
@siyengar yes as @MangeshKadam said there are no .so files in maven aar, and it doesn't work.

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
```

**Comment by ahmednasir91** [comment]
Any update?

**Comment by siyengar** [comment]
That's really strange, I'm checking the aar again.

**Comment by ahmednasir91** [comment]
I tried building locally and then included the jar, it works on x64. So it means aar has problem.

**Comment by siyengar** [comment]
Figured out the issue, the new version of gradle changed the location of intermediate aar bundle files. I'm putting up 1.0.3 now

**Comment by siyengar** [comment]
1.0.3 is released

**Comment by MangeshKadam** [comment]
compared to version 1.0.1 size of 1.0.3 is too large. Initially it was around about 850kb and now its 3.5 mb. Any specific reasons?

**Comment by siyengar** [comment]
@MangeshKadam, there are a couple of changes that affect size:
1. 2 more architectures were added, i.e. x64 and arm64. The so's from these are bigger. 
2. We upgraded to openssl 1.0.2e. To make upgrades easier we removed the custom patches that we had. This should make upgrade to future openssl versions much faster.

Even with 1.0.1 you should consider splitting up your APK by flavors so that you bundle the archs you need to target users devices. This will make it much smaller in general

**Comment by epromgalang** [comment]
I tried using 1.0.3 but I still get this error on a samsung SM-G925F (Samsung Galaxy S6 edge), Android: 5.1.1 device: 

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/asia.coins.mobile-1/base.apk"],nativeLibraryDirectories=[/data/app/asia.coins.mobile-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libconceal.so"

Am I missing something?

**Comment by siyengar** [comment]
@epromgalang i don't have access to an s6 edge phone right now. I will get one on Tuesday to repro this. Monday is a holiday in the US.

**Comment by epromgalang** [comment]
Sorry @siyengar I just figured out that the issue was just with my proguard settings which I never needed  to update when I used the prebuilt binaries. Everything works smoothly now :)

**Pull request merged**
