### PR TITLE
Adding support for 64 bit archs

### PR DESCRIPTION
**Pull request by aaalaniz**
I verified that the library works on the Galaxy S6 and Nexus 9. I have not been able to verify on 64 bit intel machine though.

### CODE REVIEW

**Comment by aaalaniz** [comment]
Is there no plan to merge this? It's been open over 2 months...

**Comment by instantiator** [comment]
+1

**Comment by jwriteclub** [comment]
+1

What's taking so long for this merge?

**Comment by njovy** [comment]
+1

**Comment by zmarkan** [comment]
+1 


Any news on this?

**Comment by siyengar** [comment]
@aaalaniz how did you build the libcrypto.a artifacts? AFAIK OpenSSL does not have a 64 bit target for android

**Comment by aaalaniz** [comment]
@siyengar I built it with the ndk

**Comment by aaalaniz** [comment]
@siyengar It's been a while so I don't quite remember all the specifics, but I used the ndk toolchains for x86_64 and armv8, pulled the version of the openssl used by conceal and built it.

**Comment by siyengar** [comment]
thanks, im trying to  reproduce the build at the moment

**Comment by aaalaniz** [comment]
yeah, no sweat....totally understand not wanting to include external binaries. thanks for revisiting this!

**Comment by siyengar** [comment]
i merged this via another pull request. Thanks @aaalaniz

**Comment by njovy** [comment]
Finally!

**Comment by siyengar** [comment]
this should now be available from maven central as version 1.0.2 or from source if you building from source

**Comment by cotfas** [comment]
Hello,

Any news on the 64bit binaries ?

**Pull request closed without merging**
